propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  client2:
    _attributes: { phpName: Client2, idMethod: native }
    id: { phpName: Id, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', primaryKey: true, autoIncrement: true, required: true }
    image_id: { phpName: ImageId, type: INTEGER, size: '10', sqlType: 'int(10) unsigned', required: false, foreignTable: image, foreignReference: id, onDelete: 'SET NULL', onUpdate: CASCADE }
    title: { phpName: Title, type: LONGVARCHAR, required: true }
    position: { phpName: Position, type: INTEGER, required: true }
    visible: { phpName: Visible, type: BOOLEAN, size: '1', sqlType: 'tinyint(1) unsigned', required: true, defaultValue: true }
    _indexes: { image_id: [image_id] }